# Site settings
title: DCog
email: json@sql.rehab
description: > # this means to ignore newlines until "baseurl:"
  Blogging is a form of distributed cognition (DCog).
  I am writing these articles to help me better understand and remember the things I learn, 
  primarily about computer science.
  Writing about something really helps me fill in the gaps by spelling it all out. 
  It's easy for me to think I understand something until I have to explain it. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pages.dcog.io" # the base hostname & protocol for your site
twitter_username: danielbushman
github_username:  danielbushman

# Build settings
markdown: kramdown
