name: uxdev.io
description: Developer Experience Advocate
meta_description: "Blogging about code and user experience."

aboutPage: true

markdown: kramdown
kramdown:
  input: GFM
highlighter: pygments

paginate: 5
baseurl: /
domain_name: 'http://uxdev.io'
google_analytics: 'UA-63530057-2'
disqus_shortname: 'uxdevio'

# Details for the RSS feed generator
url:            'http://uxdev.io'
author:         'Daniel Bushman'
authorTwitter:  '_uxdev'

permalink:       /:year/:title/

exclude: ["blog.oo3"]
timezone: America/Boise

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
