name: dcog.io 
description: Distributed cognition about code.
meta_description: "Blogging about code."

aboutPage: false

markdown: kramdown
highlighter: pygments

paginate: 5
baseurl: /
domain_name: 'http://dcog.io'
google_analytics: 'UA-63530057-2'
disqus_shortname: 'dcog'

# Details for the RSS feed generator
url:            'http://dcog.io'
author:         'Daniel Bushman'
authorTwitter:  'danielbushman'

permalink:       /:year/:title/

exclude: ["stories.dcog.io.sublime-project", "stories.dcog.io.sublime-workspace", "blog.oo3"]
timezone: America/Boise

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
